### ISSUE TITLE
Change the status of a task

### ISSUE THREAD

**Issue by maiteu** [altimetrik-onboarding-uy/muriarte#3]
As an user of the application I want to be able to change a tasks's status so they can reflect the actual progress of a TO-DO or Daily task.

**Comment by rjulianialtimetrik** [comment]
This is wrong. Only tasks of type "Daily" and "TO-DO" allow users to change their status, so not all tasks. Also, this user story has poor writing. The users don't actually need to see the tasks assigned to employees so they can change their status; the users need to be able to change a tasks's status so they can reflect the actual progress of a TO-DO or Daily task.
